blank_issues_enabled: false
contact_links:
  - name: "💬 Discussion"
    url: "https://github.com/wp-spaghetti/wonolog/discussions"
    about: "For questions, ideas, and general discussion"
    
  - name: "📖 Documentation"
    url: "https://github.com/wp-spaghetti/wonolog"
    about: "Read the documentation before asking questions"
    
  - name: "💌 Security Issues"
    url: "https://github.com/wp-spaghetti/wonolog/security"
    about: "For security vulnerabilities (private reporting)"